name = "hex-bareiss"
defaultTargets = ["HexBareiss"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "2d7f55d190cc2df9c9bf55437f344e65fbddc7c0"

[[require]]
name = "HexDeterminant"
git = "https://github.com/leanprover/hex-determinant.git"
rev = "b9b21e295175885e2ee20728c8f8a13d00e36124"

[[lean_lib]]
name = "HexBareiss"
precompileModules = true
