name = "hex-bareiss"
defaultTargets = ["HexBareiss"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "a47240943e925951a676d1a1c2f2a615ae68fdef"

[[require]]
name = "HexDeterminant"
git = "https://github.com/leanprover/hex-determinant.git"
rev = "2c122657aee7dcd9f7a619dc0d8971a3415e127a"

[[require]]
name = "HexArith"
git = "https://github.com/leanprover/hex-arith.git"
rev = "ea246536c442464a68210ecce973eb7708968f59"

[[require]]
name = "HexMatrix"
git = "https://github.com/leanprover/hex-matrix.git"
rev = "a99dc4690f411538088463b6db94e38958e65a81"

[[lean_lib]]
name = "HexBareiss"
precompileModules = true
