name = "hex-bareiss"
defaultTargets = ["HexBareiss"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "1a0fff2c8f545753b01cff0d941bf48f945cd299"

[[require]]
name = "HexDeterminant"
git = "https://github.com/leanprover/hex-determinant.git"
rev = "d542b77b0e9e6796a79efb85dd55e1b815d336bd"

[[require]]
name = "HexArith"
git = "https://github.com/leanprover/hex-arith.git"
rev = "cffb477db5d3ec87a4ef5c9466065e2e7ae03633"

[[require]]
name = "HexMatrix"
git = "https://github.com/leanprover/hex-matrix.git"
rev = "f857b2b4495dc8d9ba6583d559d2b885ccbf40fc"

[[lean_lib]]
name = "HexBareiss"
precompileModules = true
